### ISSUE TITLE
TODO for Beta 2

### ISSUE THREAD

**Issue by iksaku** [LegendOfMCPE/EssentialsPE#20]
- [x] Disable `/say` and `/me` command blocking while muted
# 
- [x] Fix PowerTool not working properly
- [x] Fix `/powertool` command messages
# 
- [x] Set commands' usage like PocketMine-MP default ones (Gray text)
# 
- [x] `essentials.vanish.pvp` Permission
# 
- [x] Implement the `/item` command :package: 
- [x] `/near` command (Search for nearby players :smile_cat: )
- [x] `/itemdb` command (Display the name, id or metadata of an item :1234: )
- [x] `/world` command (To switch between worlds :globe_with_meridians: **<=>** :globe_with_meridians: **<=>** :globe_with_meridians: )
- [x] `/essentials reload` in order to reload the EssentialsPE config :page_facing_up: 
# 
- [x] Minor Code optimization... :signal_strength: 
# 
- [x] Simplify **Seen**'s command code (`/seen <player>`) :calendar: 
# 
- [x] Signs
  - [x] Bump to API 1.3.0
  - [x] Create/Break Permission nodes (`essentials.sign.[create|break|use].[type of sign]`)
  - [x] Color Sign Permission node (`essentials.sign.color`)
  - [x] Free Sign :free: 
    - [x] `essentials.sign.break.free`
    - [x] `essentials.sign.create.free`
    - [x] `essentials.sign.use.free`
  - [x] Gamemode Sign 
    - [x] `essentials.sign.break.gamemode`
    - [x] `essentials.sign.create.gamemode`
    - [x] `essentials.sign.use.gamemode`
  - [x] Heal Sign
    - [x] `essentials.sign.break.heal`
    - [x] `essentials.sign.create.heal`
    - [x] `essentials.sign.use.heal`
  - [x] Repair Sign :collision: 
    - [x] `essentials.sign.break.repair`
    - [x] `essentials.sign.create.repair`
    - [x] `essentials.sign.use.repair`
  - [x] Time sign :clock3: 
    - [x] `essentials.sign.break.time`
    - [x] `essentials.sign.create.time`
    - [x] `essentials.sign.use.time`
  - [x] Teleport sign 
    - [x] `essentials.sign.break.teleport`
    - [x] `essentials.sign.create.teleport`
    - [x] `essentials.sign.use.teleport`
# 
- [x] Auto-AFK-Kick :alarm_clock: 
# 
- [x] TempBan command with a comma delimiter... (/temban iksaku 2d,3m,1w,1mo,89s)
# 
- [x] **_Surprise 1**_ :gift: _World switcher!_ `/world <world name>`
- [x] **_Surprise 2**_ :gift_heart: _Inventory See_! **BETA!** `/invsee <player>`
