### ISSUE TITLE
To-do List for Beta 3

### ISSUE THREAD

**Issue by iksaku** [LegendOfMCPE/EssentialsPE#28]
#### Add or improve
- [x] `/nuke` Command
- [x] Automatic Godmode switch using `/tgm` alias
- [x] `/suicide` Command (To encourage the use of `/kill` just to kill others)
- [x] `/spawn` Command (Teleport to server's main spawn location)
#### To Test
- [x] /nuke
- [x] /sudo
- [x] /back
- [x] /tpall
- [x] /tphere
#### Override
- [x] `/kill` Command (Just to kill other players)
#### Remove
- [x] Remove `/invsee` Command (It's nothing related to the original one)
# To Release
- [x] Compatibility with Minecraft PE 0.10
- [x] _**WARPS!**_ :gift:  Surprise!
